# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib b64, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_b64__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_b64__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}


`alphabet_` <- function(`which`) {
  .savvy_wrap_Alphabet(.Call(savvy_alphabet___impl, `which`))
}

#' Utility Functions
#'
#' Functions to perform common tasks when working with base64 encoded strings.
#'
#' @details
#'
#' `b64_chunk()` splits a character vector of base64 encoded strings into chunks of a
#' specified width.
#'
#' `b64_wrap()` wraps a character vector of base64 encoded strings with a newline character.
#'
#' @returns
#'
#' - `b64_chunk()` returns a list of character vectors.
#' - `b64_wrap()` returns a scalar character vector.
#'
#' @examples
#' encoded <- encode("Hello, world!")
#' chunked <- b64_chunk(encoded, 4)
#' chunked
#'
#' b64_wrap(chunked, "\n")
#' @param width a numeric scalar defining the width of the chunks. Must be divisible by 4.
#' @param encoded a character vector of base64 encoded strings.
#' @export
#' @rdname utils
`b64_chunk` <- function(`encoded`, `width`) {
  .Call(savvy_b64_chunk__impl, `encoded`, `width`)
}

#' @param chunks a character vector of base64 encoded strings.
#' @param newline a character scalar defining the newline character.
#' @export
#' @rdname utils
`b64_wrap` <- function(`chunks`, `newline`) {
  .Call(savvy_b64_wrap__impl, `chunks`, `newline`)
}


`decode_` <- function(`input`, `engine`) {
  `engine` <- .savvy_extract_ptr(`engine`, "GeneralPurpose")
  .Call(savvy_decode___impl, `input`, `engine`)
}


`decode_as_string_` <- function(`what`, `engine`, `split` = NULL) {
  `engine` <- .savvy_extract_ptr(`engine`, "GeneralPurpose")
  .Call(savvy_decode_as_string___impl, `what`, `engine`, `split`)
}


`decode_file_` <- function(`path`, `engine`) {
  `engine` <- .savvy_extract_ptr(`engine`, "GeneralPurpose")
  .Call(savvy_decode_file___impl, `path`, `engine`)
}


`decode_vectorized_` <- function(`what`, `engine`) {
  `engine` <- .savvy_extract_ptr(`engine`, "GeneralPurpose")
  .Call(savvy_decode_vectorized___impl, `what`, `engine`)
}


`encode_` <- function(`what`, `engine`) {
  `engine` <- .savvy_extract_ptr(`engine`, "GeneralPurpose")
  .Call(savvy_encode___impl, `what`, `engine`)
}


`encode_file_` <- function(`path`, `engine`) {
  `engine` <- .savvy_extract_ptr(`engine`, "GeneralPurpose")
  .Call(savvy_encode_file___impl, `path`, `engine`)
}


`encode_vectorized_` <- function(`what`, `engine`) {
  `engine` <- .savvy_extract_ptr(`engine`, "GeneralPurpose")
  .Call(savvy_encode_vectorized___impl, `what`, `engine`)
}


`engine_` <- function(`which`) {
  .savvy_wrap_GeneralPurpose(.Call(savvy_engine___impl, `which`))
}


`get_alphabet_` <- function(`alphabet`) {
  `alphabet` <- .savvy_extract_ptr(`alphabet`, "Alphabet")
  .Call(savvy_get_alphabet___impl, `alphabet`)
}


`new_alphabet_` <- function(`chars`) {
  .savvy_wrap_Alphabet(.Call(savvy_new_alphabet___impl, `chars`))
}


`new_config_` <- function(`encode_padding`, `decode_padding_trailing_bits`, `decode_padding_mode`) {
  .savvy_wrap_GeneralPurposeConfig(.Call(savvy_new_config___impl, `encode_padding`, `decode_padding_trailing_bits`, `decode_padding_mode`))
}


`new_engine_` <- function(`alphabet`, `config`) {
  `alphabet` <- .savvy_extract_ptr(`alphabet`, "Alphabet")
  `config` <- .savvy_extract_ptr(`config`, "GeneralPurposeConfig")
  .savvy_wrap_GeneralPurpose(.Call(savvy_new_engine___impl, `alphabet`, `config`))
}


`print_config_` <- function(`config`) {
  `config` <- .savvy_extract_ptr(`config`, "GeneralPurposeConfig")
  .Call(savvy_print_config___impl, `config`)
}


`print_engine_` <- function(`engine`) {
  `engine` <- .savvy_extract_ptr(`engine`, "GeneralPurpose")
  .Call(savvy_print_engine___impl, `engine`)
}

### wrapper functions for Alphabet


`.savvy_wrap_Alphabet` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- c("Alphabet", "savvy_b64__sealed")
  e
}



`Alphabet` <- new.env(parent = emptyenv())

### associated functions for Alphabet



class(`Alphabet`) <- c("Alphabet__bundle", "savvy_b64__sealed")

#' @export
`print.Alphabet__bundle` <- function(x, ...) {
  cat('Alphabet\n')
}

### wrapper functions for GeneralPurpose


`.savvy_wrap_GeneralPurpose` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- c("GeneralPurpose", "savvy_b64__sealed")
  e
}



`GeneralPurpose` <- new.env(parent = emptyenv())

### associated functions for GeneralPurpose



class(`GeneralPurpose`) <- c("GeneralPurpose__bundle", "savvy_b64__sealed")

#' @export
`print.GeneralPurpose__bundle` <- function(x, ...) {
  cat('GeneralPurpose\n')
}

### wrapper functions for GeneralPurposeConfig


`.savvy_wrap_GeneralPurposeConfig` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- c("GeneralPurposeConfig", "savvy_b64__sealed")
  e
}



`GeneralPurposeConfig` <- new.env(parent = emptyenv())

### associated functions for GeneralPurposeConfig



class(`GeneralPurposeConfig`) <- c("GeneralPurposeConfig__bundle", "savvy_b64__sealed")

#' @export
`print.GeneralPurposeConfig__bundle` <- function(x, ...) {
  cat('GeneralPurposeConfig\n')
}

